### PR TITLE
Fix issue #40 db-fixture-rest-api live reloading

### PR DESCRIPTION
**Pull request by foodcourt2021**

### CODE REVIEW

**Comment by ashleydavis** [comment]
Thanks so much for your contribution, I just added one question that I was wondering about.

**Comment by foodcourt2021** [comment]
Hi Ashley,

Thanks for your feedback! I am wondering where I can see your question?

**Comment by ashleydavis** [comment]
> Hi Ashley,
> 
> Thanks for your feedback! I am wondering where I can see your question?

If you just scroll back a bit in this PR, you should see it.

**Comment by foodcourt2021** [comment]
Sorry Ashley, I am new to PR and I was still not able to see your question...

**Comment by ashleydavis** [comment]
> Sorry Ashley, I am new to PR and I was still not able to see your question...

Hey no problem, I tagged you in the question, hopefully you'll be notified about it.

**Comment by foodcourt2021** [comment]
Hi Ashley, sorry for the inconvenience. I waited a little bit and still didn't see the notification :(
Is it possible for your to post the question as a comment here? Thank you for your time!

**Comment by ashleydavis** [comment]
@foodcourt2021 here is a screenshot of the question that I can see earlier in this PR:

image

**Comment by foodcourt2021** [comment]
Hi Ashley,

Thanks for posting the screenshot! If I just have

```
"start": "nodemon --legacy-watch --watch \"fixtures/**/*\" --watch ./src/index.js
```

without the `--delay` option, I will keep getting the following messages until the whole app crashes.
The `--delay 5` works for me. I have not tried anything less than 5 seconds. Probably they will also work.

```
db-fixture-rest-api    | [nodemon] 1.18.9
db-fixture-rest-api    | [nodemon] to restart at any time, enter `rs`
db-fixture-rest-api    | [nodemon] watching: ./src/index.js
db-fixture-rest-api    | [nodemon] starting `nodemon --legacy-watch --watch ./src/index.js`
db-fixture-rest-api    | [nodemon] 1.18.9
db-fixture-rest-api    | [nodemon] to restart at any time, enter `rs`
db-fixture-rest-api    | [nodemon] watching: ./src/index.js
```

**Comment by ashleydavis** [comment]
Ok thanks so much. I'll merge and test it myself.

Please send me an email on ashley at codecapers.com.au so I can make sure your on my list for the 2nd edition of the book.

**Pull request merged**
